name: Continuous Integration

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint-eslint:
    name: 'Lint: ESLint'
    uses: ./.github/workflows/npm-script.yml
    with:
      script: lint:eslint

  lint-prettier:
    name: 'Lint: Prettier'
    uses: ./.github/workflows/npm-script.yml
    with:
      script: lint:prettier

  lint-commits:
    name: 'Lint: Commits'
    uses: ./.github/workflows/conventional-commits.yml

  lint-pr:
    name: 'Lint: PR title'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-unit:
    name: 'Test: Unit'
    uses: ./.github/workflows/npm-script.yml
    with:
      script: coverage
